=== DenitsaStoianova/XML-Programming/GamesCatalog/game_catalog.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT game_catalog (series)>
        <!ELEMENT series (basic_info, games)>
        <!ELEMENT basic_info (title, release_year, developer)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT release_year (#PCDATA)>
        <!ELEMENT developer (studio_name, nationality, founder)>
        <!ELEMENT studio_name (#PCDATA)>
        <!ELEMENT nationality (#PCDATA)>
        <!ELEMENT founder (#PCDATA)>
        <!ELEMENT games (game+)>
        <!ELEMENT game (basic_info, price, language, image, system_requirements, descriptions)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT language (#PCDATA)>
        <!ELEMENT image (#PCDATA)>
        <!ELEMENT system_requirements (processor, os, sound_card, available_space)>
        <!ELEMENT processor (#PCDATA)>
        <!ELEMENT os (#PCDATA)>
        <!ELEMENT sound_card (#PCDATA)>
        <!ELEMENT available_space (#PCDATA)>
        <!ELEMENT descriptions (description+)>
        <!ELEMENT description (part_number, part_title, text)>
        <!ELEMENT part_number (#PCDATA)>
        <!ELEMENT part_title (#PCDATA)>
        <!ELEMENT text (#PCDATA)>

        <!ATTLIST series srsId CDATA #REQUIRED>
        <!ATTLIST game code CDATA #REQUIRED category CDATA #REQUIRED>
        <!ATTLIST price currency CDATA #REQUIRED>
        <!ATTLIST sound_card has (Да|Не) "Не">
        <!ATTLIST available_space unit CDATA #REQUIRED>
        <!ATTLIST nationality code CDATA #REQUIRED>
        <!ATTLIST os bits CDATA #REQUIRED>

=== DenitsaStoianova/XML-Programming/GamesCatalog/valid_xml_3.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE game_catalog SYSTEM "game_catalog.dtd">

<game_catalog>
    <series srsId="GTA3">
        <basic_info>
            <title>Grand Theft Auto</title>
            <release_year>1997</release_year>
            <developer>
                <studio_name>Рокстар Норт</studio_name>
                <nationality code="SCT">Шотландски разработчик</nationality>
                <founder>Майк Дейли</founder>
            </developer>
        </basic_info>
        <games>
            <game code="017c884d" category="Излезли Игри">
                <basic_info>
                    <title>Grand Theft Auto: San Andreas</title>
                    <release_year>2005</release_year>
                    <developer>
                        <studio_name>Take 2</studio_name>
                        <nationality code="US">Американски разработчик</nationality>
                        <founder>Райън Брент</founder>
                    </developer>
                </basic_info>
                <price currency="лв">31.66</price>
                <language>Английски</language>
                <image>GTA_San_Andreas.jpg</image>
                <system_requirements>
                    <processor>Pentium III или по-добър.</processor>
                    <os bits="2000/XP">Само Windows</os>
                    <sound_card has="Да"/>
                    <available_space unit="гигабайта">3.6</available_space>
                </system_requirements>
                <descriptions>
                    <description>
                        <part_number>Част 1</part_number>
                        <part_title>Основно</part_title>
                        <text>
                            Ако поне веднъж сте играли на някоя от сериите на GTA, то със сигурност знаете какво представлява тръпката от тази екшън игра от трето лице. За тези, които не познават заглавието Grand Theft Auto, ще поясним, че в него се водят гангстерски войни по американските гета, където е задължително да имаш кола, за да подсигуриш придвижването си из кварталите. Последните обаче могат да бъдат много опасни, така че е нужно да имате оръжие под ръка за всеки случай.
                        </text>
                    </description>
                    <description>
                        <part_number>Част 2</part_number>
                        <part_title>Геймплей</part_title>
                        <text>
                            В петото издание на GTA ще видите нови коли, мотори, хеликоптери и какви ли не превозни средства, с които да се придвижвате и да давате отпор на лошите гангстери. На разположение са и нови оръжия, сред които бухалки, пистолети, пушки и какво ли още не. Ако пък не разполагате с оръжие в началото, то може да раздадете юмручно право на тези, които Ви се правят на тарикати.
                        </text>
                    </description>
                    <description>
                        <part_number>Част 3</part_number>
                        <part_title>Графика и звук</part_title>
                        <text>
                            Това е един от най-реалните екшъни, които сме виждали. И, макар че е създаден през 2005 година, може да се сравни и с най-големите си съвременни претенденти. Играейки на GTA San Andreas ще се почувствате все едно, че наистина сте влезли в гангстерския свят в щатите. Горещите емоции са допълнени от напрегната музика и реалистични звукови ефекти, които ще Ви впечатлят.
                        </text>
                    </description>
                </descriptions>
            </game>
            <game code="8a399d13" category="Излезли Игри">
                <basic_info>
                    <title>Grand Theft Auto IV – Complete Edition</title>
                    <release_year>2010</release_year>
                    <developer>
                        <studio_name>Рокстар Норт</studio_name>
                        <nationality code="SE">Шотландски разработчик</nationality>
                        <founder>Майк Дейли</founder>
                    </developer>
                </basic_info>
                <price currency="лв">29.33</price>
                <language>Английски</language>
                <image>GTA_Compl_Ed.jpg</image>
                <system_requirements>
                    <processor> Intel Core 2 Duo 1.8GHz / AMD Athlon X2 64 2.4GHz или по-добър</processor>
                    <os bits="32-bit">Windows XP/Vista/7/8/8.1/10</os>
                    <sound_card has="Да"/>
                    <available_space unit="гигабайта">25</available_space>
                </system_requirements>
                <descriptions>
                    <description>
                        <part_number>Част 1</part_number>
                        <part_title>Основно</part_title>
                        <text>
                            Това е екшън – приключенска игра с отворен свят, в която можете да демонстрирате своите шофьорски умения карайки автомобили, мотори, камиони и други превозни средства, както и да докажете, че сте опитен уличен боец. Играта е забранена за непълнолетни лица и може да се играе само от геймъри, които са навършили 18 години.
                        </text>
                    </description>
                    <description>
                        <part_number>Част 2</part_number>
                        <part_title>Геймплей</part_title>
                        <text>
                            В четвъртата част на GTA и придружаващите я епизоди ще се изправите срещу гангстери и корумпирани ченгета. Вие ще се потопите в свят на яки автомобили, оръжия, секс и наркотици. Гангстерите ще Ви дебнат от всеки ъгъл, така че е добре да реагирате своевременно и да демонстрирате, че нямате никакво намерение да се предадете и да си стоите кротко вкъщи.
                        </text>
                    </description>
                    <description>
                        <part_number>Част 3</part_number>
                        <part_title>Графика и звук</part_title>
                        <text>
                            Реалистичността на отворения свят предоставен в Grand Theft Auto IV (Complete Edition), е невероятна. Колите, хората, боищата и всичко друго е извадено от истински живот, такъв какъвто може да се види по гетата на САЩ. Към всичко това е приложен много здрав саундтрак, за да се изкефите максимално на това заглавие. Имайте предвид, че играейки ще чувате псувни и ругатни, ще виждате проституиращи момичета и ще чувате болките на противниците. Всичко това са основателни причини новото GTA да се предлага само за пълнолетни играчи.
                        </text>
                    </description>
                </descriptions>
            </game>
        </games>
    </series>
</game_catalog>

=== DenitsaStoianova/XML-Programming/GamesCatalog/valid_xml_5.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE game_catalog SYSTEM "game_catalog.dtd">

<game_catalog>
    <series srsId="M5">
        <basic_info>
            <title>Minecraft</title>
            <release_year>2009</release_year>
            <developer>
                <studio_name>Mojang Studios</studio_name>
                <nationality code="SE">Шведски разработчик</nationality>
                <founder>Маркус Персон</founder>
            </developer>
        </basic_info>
        <games>
            <game code="86622d87" category="Излезли Игри">
                <basic_info>
                    <title>Minecraft: Windows 10 Edition</title>
                    <release_year>2015</release_year>
                    <developer>
                        <studio_name>EA Gothenburg</studio_name>
                        <nationality code="SE">Шведски разработчик</nationality>
                        <founder>Бен Уолк</founder>
                    </developer>
                </basic_info>
                <price currency="лв">75.27</price>
                <language>Английски</language>
                <image>Minecraft_10.jpg</image>
                <system_requirements>
                    <processor>Intel Core i3-3210 3.2 GHz / AMD A8-7600 APU 3.1 GHz или по-добър</processor>
                    <os bits="64-bit">Windows 10</os>
                    <sound_card has="Да"/>
                    <available_space unit="гигабайта">2</available_space>
                </system_requirements>
                <descriptions>
                    <description>
                        <part_number>Част 1</part_number>
                        <part_title>Основно</part_title>
                        <text>
                            Повечето от геймърите са истински запалени фенове на Майнкрафт, а ако не се причисляваш към тях, то със сигурност поне си чувал за съществуването на играта, с която можеш да построиш всичко.
                        </text>
                    </description>
                    <description>
                        <part_number>Част 2</part_number>
                        <part_title>Геймплей</part_title>
                        <text>
                            Играта като цяло има няколко режима – survival (играчът трябва да събира ресурси и да строи сгради с цел оживяване), creative (основен режим, наподобяващ „оцеляване“, но с повече възможности за строене), hardcore (най-трудният от всички), adventure (без възможност за директно разрушаване, играчът трябва да произвежда различни неща) ,spectator (можете да летите наоколо) ,demo (демо режим за потребители, които не са купили играта).
                        </text>
                    </description>
                    <description>
                        <part_number>Част 3</part_number>
                        <part_title>Графика и звук</part_title>
                        <text>
                            Добавени са и други интересни функции, като например по-разширен контрол и възможността за записване и споделяне на всичко, което се случва в играта чрез game DVR. Също както предшествениците си тази версия има много елементи на оцеляване.
                        </text>
                    </description>
                </descriptions>
            </game>
        </games>
    </series>
</game_catalog>

=== DenitsaStoianova/XML-Programming/GamesCatalog/valid_xml_2.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE game_catalog SYSTEM "game_catalog.dtd">

<game_catalog>
    <series srsId="FA2">
        <basic_info>
            <title>FIFA</title>
            <release_year>1993</release_year>
            <developer>
                <studio_name>Electronic Arts</studio_name>
                <nationality code="CA">Канадски разработчик</nationality>
                <founder>Трип Хоукинс</founder>
            </developer>
        </basic_info>
        <games>
            <game code="KG-67495" category="Излезли Игри">
                <basic_info>
                    <title>FIFA 20</title>
                    <release_year>2019</release_year>
                    <developer>
                        <studio_name>Electronic Arts</studio_name>
                        <nationality code="CA">Канадски разработчик</nationality>
                        <founder>Трип Хоукинс</founder>
                    </developer>
                </basic_info>
                <price currency="лв">66.46</price>
                <language>Английски</language>
                <image>FIFA_20.jpg</image>
                <system_requirements>
                    <processor>Phenom II X4 965 or Equivalent / i3-2100 or Equivalent или по-добър</processor>
                    <os bits="64-bit">Windows 7/8.1/10</os>
                    <sound_card has="Да"/>
                    <available_space unit="гигабайта">50</available_space>
                </system_requirements>
                <descriptions>
                    <description>
                        <part_number>Част 1</part_number>
                        <part_title>Основно</part_title>
                        <text>
                            Изберете отбора си и го отведете до висините на премиер лигата или всеки друг шампионат, който ви е по сърце. Това е същността на FIFA 20.
                        </text>
                    </description>
                    <description>
                        <part_number>Част 2</part_number>
                        <part_title>Геймплей</part_title>
                        <text>
                            Играта, както се очаква от популярният и успешен франчайз, предлага да избирате между истински отбори от целия свят и техните стадиони.
                        </text>
                    </description>
                    <description>
                        <part_number>Част 3</part_number>
                        <part_title>Графика и звук</part_title>
                        <text>
                            Можете да менажирате и свой собствен отбор, започвайки от играчите или да използвате играчи от реалния свят, които изглеждат досущ като живите си двойници, заради прекрасната графика, която са осигурили от EA Games.
                        </text>
                    </description>
                </descriptions>
            </game>
            <game code="JT-67408" category="Излезли Игри">
                <basic_info>
                    <title>FIFA 21</title>
                    <release_year>2019</release_year>
                    <developer>
                        <studio_name>Electronic Arts</studio_name>
                        <nationality code="CA">Канадски разработчик</nationality>
                        <founder>Трип Хоукинс</founder>
                    </developer>
                </basic_info>
                <price currency="лв">79.18</price>
                <language>Английски</language>
                <image>FIFA_21.jpg</image>
                <system_requirements>
                    <processor>ПРОЦЕСОР: Athlon X4 880K / Core i3-6100 или по-добър</processor>
                    <os bits="64-bit"> Windows 7/8.1/10</os>
                    <sound_card has="Да"/>
                    <available_space unit="гигабайта">50</available_space>
                </system_requirements>
                <descriptions>
                    <description>
                        <part_number>Част 1</part_number>
                        <part_title>Основно</part_title>
                        <text>
                            На улицата и на стадиона, FIFA 21 предлага повече варианти за игра от всякога. В тази част на сериите FIFA ще бъдеш възнаграждаван за креативност и контрол върху терена. Създавай повече възможности за попадение с изцяло новата динамична система за атака в най-интелигентния FIFA геймплей до момента.
                        </text>
                    </description>
                    <description>
                        <part_number>Част 2</part_number>
                        <part_title>Геймплей</part_title>
                        <text>
                            Нова „Agile Dribbling“ система ти предоставя нужните средства да разгърнеш креативността си в ситуации 1-1. Използвай бърза работа с краката, по-реактивен близък контрол и нови умения за движение, като заблуждаващото въртене на топката за преминаване покрай защитниците на съперника.
                        </text>
                    </description>
                    <description>
                        <part_number>Част 3</part_number>
                        <part_title>Графика и звук</part_title>
                        <text>
                            Виж как нападатели от световна величина бягат в линия с последния защитник, креативни плеймейкъри намират място за игра с топката, а полузащитници блокират чисти пасове, благодарение на подобрена ориентация на играчите във времето и пространството.
                        </text>
                    </description>
                </descriptions>
            </game>
        </games>
    </series>
</game_catalog>

=== DenitsaStoianova/XML-Programming/GamesCatalog/valid_xml_4.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE game_catalog SYSTEM "game_catalog.dtd">

<game_catalog>
    <series srsId="NFS4">
        <basic_info>
            <title>Need for Speed</title>
            <release_year>1994</release_year>
            <developer>
                <studio_name>Electronic Arts</studio_name>
                <nationality code="CA">Канадски разработчик</nationality>
                <founder>Трип Хоукинс</founder>
            </developer>
        </basic_info>
        <games>
            <game code="2bbfe09c" category="Излезли Игри">
                <basic_info>
                    <title>Need for Speed: Heat</title>
                    <release_year>2019</release_year>
                    <developer>
                        <studio_name>EA Gothenburg</studio_name>
                        <nationality code="CH">Шведски разработчик</nationality>
                        <founder>Ben Walke</founder>
                    </developer>
                </basic_info>
                <price currency="лв">50.62</price>
                <language>Английски</language>
                <image>NFS_Heat.jpg</image>
                <system_requirements>
                    <processor>Intel Core i5 3570 / AMD FX 6350 или по-добър</processor>
                    <os bits="32-bit">Windows</os>
                    <sound_card has="Да"/>
                    <available_space unit="гигабайта">50</available_space>
                </system_requirements>
                <descriptions>
                    <description>
                        <part_number>Част 1</part_number>
                        <part_title>Основно</part_title>
                        <text>
                            Градът в играта – Палм Сити е вдъхновен от Флорида и създава усещането за приключение с привкус на лятна почивка. През деня основната роля на играчът е да разглежда красивият отворен свят на играта и да участва в легалните състезания, провеждащи се в Палм Сити.
                        </text>
                    </description>
                    <description>
                        <part_number>Част 2</part_number>
                        <part_title>Геймплей</part_title>
                        <text>
                            Същинският геймплей на играта започва щом падне нощта. Тогава пред играча се отварят куп нови и рисковани възможности. Нощтните състезания са нелегални и залозите са много по-големи. За разлика от дневните състезания, тук вече не става въпрос за пари, а за репутация. Колкото по-голяма репутация имате, толкова по-търсен ставате от полицията. В същото време пред вас се разкриват и толкова повече нови коли и ъпгрейди.
                        </text>
                    </description>
                    <description>
                        <part_number>Част 3</part_number>
                        <part_title>Графика и звук</part_title>
                        <text>
                            Играта разполага с апликация, която ви позволява да правите ъпгрейди по колите си, дори когато не сте у дома и да ги изпращате в гаража за момента, когато сте пред компютъра.
                        </text>
                    </description>
                </descriptions>
            </game>
            <game code="86622d87" category="Излезли Игри">
                <basic_info>
                    <title>Need for Speed: Payback</title>
                    <release_year>2017</release_year>
                    <developer>
                        <studio_name>EA Gothenburg</studio_name>
                        <nationality code="SE">Шведски разработчик</nationality>
                        <founder>Ben Walke</founder>
                    </developer>
                </basic_info>
                <price currency="лв">29.16</price>
                <language>Английски</language>
                <image>NFS_Payback.jpg</image>
                <system_requirements>
                    <processor>Intel i3 6300 @ 3.8GHz / AMD FX 8150 @ 3.6GHz или по-добър</processor>
                    <os bits="64-bit">Windows 7, Windows 8.1 или Windows 10</os>
                    <sound_card has="Да"/>
                    <available_space unit="гигабайта">30</available_space>
                </system_requirements>
                <descriptions>
                    <description>
                        <part_number>Част 1</part_number>
                        <part_title>Основно</part_title>
                        <text>
                            Need for Speed: Payback ще ви позволи да се състезавате с 74 модела коли, всички производители, с изключение на Тойота и Ферари, които са отказали да предоставят лиценз за използването на техните модели коли.
                        </text>
                    </description>
                    <description>
                        <part_number>Част 2</part_number>
                        <part_title>Геймплей</part_title>
                        <text>
                            Освен, че е рейсинг игра – Need for Speed: Payback се развива и на карта от отворен тип, като действието се развива в Fortune Valley. Играта, разбира се, се фокусира върху бясното шофиране и има три главни героя, всеки с различни способности, които работят в екип, за да създадът сцени, достойни за следващият екшън блокбъстър на Холивуд!
                        </text>
                    </description>
                    <description>
                        <part_number>Част 3</part_number>
                        <part_title>Графика и звук</part_title>
                        <text>
                            Графиката е на най-високо равнище и ще Ви пренесе в непознати светове, виждайки красиви изображения.
                        </text>
                    </description>
                </descriptions>
            </game>
        </games>
    </series>
</game_catalog>
